language: go

go:
  - 1.14.x
  - tip

os:
  - linux

services:
  - docker

branches:
  only:
    - main
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

addons:
  sonarcloud:
    organization: "xmidt-org"
    token:
      secure: "AmrBoJpfpOGeJkxtyBLNojHffbMUe0DnmExcFn9KJMKNXVCH7LM6QNs/nrTRbnRcDPMvyrqqbfoo9mAX86BkW8T6TbwvO2TJX7TMLFka7dVNlbX7kvIhLnJKtT/CimMu1fb1V2kEI0h6y9u961pZjU6qtP8jozzLyfC9XO0atSL5AVo0ZcVvbLrr8sQ9THk/HQBuGE64/45ZYtpCMPX6VaP5/XoUjJuef3GoFogOK+hDH5FCudS5dU/hEcJP81/cBhtI13Q/YSRreAHL6xd+YVSiub7uR6Jszxr2z6eG9Bc/f3yvsdTkp1WvAhQbyiD+W0WdCawd+JhXYggep+iVuZnGmRihtV2tUcgAHxYq6kBbeXlYWXvbqqiVcb0VnN/Vi+mE4OYLqrJWM6SDXCTJdksFEgX1wrX/EyUUpfQI/hrnQiDAoInsyx67Nt4XAzKL2up2kAXQ5so8ZTE6sVaJGAtJz6yAxtwl/fnIZBgUALxbkvzz3mafapmPQLOMFWFm5/FRFrac5Sh5aJx2ExIuGPTHLyDqcSwjjyszqjQ6mkhIXQ2Ai0n9e5/gnPFUJv0rX3IJqwP5K23alnvPl/7GvrlkczOgBJXasyMW1WFmoRGCB+vkxYSdAChIgqCPnz4saAO42zCIVMxX0iBHCCTCqAwtHQn5eSFy+QJYLUkhqVE="

script:
  - make style codecov
  - sonar-scanner -Dproject.settings=./.sonar-project.properties

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    # - stage: integration
    #   name: "Integration Tests"
    #   if: branch = main
    #   script:
    #     - make it
    - stage: tag
      name: "Tag For Release"
      if: branch = main && type = push
      before_script:
        - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
      script:
        - export OLD_VERSION=$(make version)
        - git config --global user.name "xmidt-bot"
        - git config --global user.email "$BOT_EMAIL"
        - export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v\d+.\d+.\d+)\].*/s')
        - export TODAY=`date +'%m/%d/%Y'`
        - export NOTES=$(cat CHANGELOG.md | perl -0777 -ne 'print "$ENV{TODAY}\n\n$1\n" if /.*## \[$ENV{TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
        - if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" ]]; then git tag -a "$TAG" -m "$NOTES"; git push origin --tags; echo $?; fi
    - stage: release
      name: "Make a Release"
      if: branch != main
      script: skip
      before_deploy:
        - make release-artifacts
      deploy:
        on:
          all_branches: true
          tags: true
        provider: releases
        api_key: "$GH_TOKEN"
        file_glob: true
        file: ./.ignore/*
        skip_cleanup: true
    - stage: docker-release
      name: "Make Docker Release"
      if: branch != main
      script: skip
      deploy:
        - provider: script
          script: bash deploy/docker_push
          on:
            all_branches: true
            tags: true
