version = 1
SPDX-PackageName = "argus"
SPDX-PackageSupplier = "John Bass <john_bass2@cable.comcast.com>"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/argus"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".dockerignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".whitesource"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.mod"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".release/helm/argus/.helmignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integtests/yugabyte/docFiles/create_db.cql"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "NOTICE"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
