// SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
// SPDX-License-Identifier: Apache-2.0
package dynamodb

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsConfigV2 "github.com/aws/aws-sdk-go-v2/config"
	awsCredsV2 "github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/go-playground/validator/v10"
	"github.com/xmidt-org/argus/model"
	"github.com/xmidt-org/argus/store"
	"github.com/xmidt-org/argus/store/db/metric"
	"github.com/xmidt-org/httpaux/erraux"
)

// DynamoDB is the path to the configuration structure
// needed to connect to a dynamo DB instance.
const DynamoDB = "dynamo"

const (
	defaultTable      = "gifnoc"
	defaultMaxRetries = 3
)

var validate *validator.Validate

var errHTTPBadRequest = &erraux.Error{
	Err:  errors.New("bad request to dynamodb"),
	Code: http.StatusBadRequest,
}

func init() {
	validate = validator.New()
}

// Config contains all fields needed to establish a connection
// with a dynamoDB instance.
type Config struct {
	// Table is the name of the target DB table.
	// (Optional) Defaults to 'gifnoc'
	Table string

	// Endpoint is the HTTP(S) URL to the DB.
	// (Optional) Defaults to endpoint generated by the aws sdk.
	Endpoint string

	// Region is the AWS region of the running DB.
	Region string `validate:"required"`

	// MaxRetries is the number of times DB operations will be retried on error.
	// (Optional) Defaults to 3.
	MaxRetries int

	// GetAllLimit is the maximum number of items to get at a time.
	// (Optional) defaults to no limit
	GetAllLimit int32

	// AccessKey is the AWS AccessKey credential.
	AccessKey *string

	// SecretKey is the AWS SecretKey credential.
	SecretKey *string

	// DisableDualStack indicates whether the connection to the DB should be
	// dual stack (IPv4 and IPv6).
	// (Optional) Defaults to False.
	DisableDualStack bool

	// If roleBasedAccess is enabled, accessKey and secretKey will be fetched using IAM temporary credentials
	RoleBasedAccess bool

	// Mechanically identical to RoleBasedAccess, but with descriptive name
	UseDefaultCredentialChain bool
}

// dao adapts the underlying dynamodb data service to match
// the store.DAO (currently named store.S but we should rename it) interface.
type dao struct {
	s service
}

func NewDynamoDB(config Config, measures metric.Measures) (store.S, error) {
	if config.Table == "" {
		config.Table = defaultTable
	}
	if config.MaxRetries == 0 {
		config.MaxRetries = defaultMaxRetries
	}
	err := validate.Struct(config)
	if err != nil {
		return nil, err
	}

	var awsCfg aws.Config
	if config.RoleBasedAccess || config.UseDefaultCredentialChain {
		awsRegion, err := getAwsRegionForRoleBasedAccess(config)
		if err != nil {
			return nil, err
		}

		// Use the default credential chain (env, shared config, EC2, etc)
		awsCfg, err = awsConfigV2.LoadDefaultConfig(context.Background(),
			awsConfigV2.WithRegion(awsRegion),
		)
		if err != nil {
			return nil, err
		}
		if config.Endpoint != "" {
			awsCfg.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(
				func(service, region string, options ...interface{}) (aws.Endpoint, error) {
					return aws.Endpoint{URL: config.Endpoint}, nil
				},
			)
		}
	} else {
		if config.AccessKey == nil || config.SecretKey == nil {
			return nil, fmt.Errorf("accessKey and secretKey must be provided when roleBasedAccess is false")
		}
		awsCfg, err = awsConfigV2.LoadDefaultConfig(context.Background(),
			awsConfigV2.WithRegion(config.Region),
			awsConfigV2.WithCredentialsProvider(awsCredsV2.NewStaticCredentialsProvider(*config.AccessKey, *config.SecretKey, "")),
		)
		if err != nil {
			return nil, err
		}
		if config.Endpoint != "" {
			awsCfg.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(
				func(service, region string, options ...interface{}) (aws.Endpoint, error) {
					return aws.Endpoint{URL: config.Endpoint}, nil
				},
			)
		}
	}

	// TODO: Update newService to accept aws.Config from v2 SDK, or adapt as needed
	svc, err := newService(awsCfg, config.Table, config.GetAllLimit, &measures)
	if err != nil {
		return nil, err
	}

	svc = newInstrumentingService(&dynamoMeasuresUpdater{measures: &measures}, svc, time.Now)
	return &dao{
		s: svc,
	}, nil
}

func getAwsRegionForRoleBasedAccess(config Config) (string, error) {
	awsRegion := config.Region

	if len(awsRegion) == 0 {
		awsRegion = os.Getenv("AWS_REGION")
	}

	if len(awsRegion) == 0 {
		return "", fmt.Errorf("%s", "Aws region is not provided")
	}

	return awsRegion, nil
}

func (d dao) Push(key model.Key, item store.OwnableItem) error {
	_, err := d.s.Push(key, item)
	return sanitizeError(err)
}

func (d dao) Get(key model.Key) (store.OwnableItem, error) {
	item, _, err := d.s.Get(key)
	return item, sanitizeError(err)
}

func (d *dao) Delete(key model.Key) (store.OwnableItem, error) {
	item, _, err := d.s.Delete(key)
	return item, sanitizeError(err)
}

func (d *dao) GetAll(bucket string) (map[string]store.OwnableItem, error) {
	items, _, err := d.s.GetAll(bucket)
	return items, sanitizeError(err)
}

func sanitizeError(err error) error {
	if err == nil {
		return nil
	}
	// AWS SDK v2 error handling: check for smithy error with ErrorCode()
	type errorCode interface {
		ErrorCode() string
	}
	var awsErr errorCode
	if errors.As(err, &awsErr) {
		if awsErr.ErrorCode() == "ValidationException" {
			return store.SanitizedError{Err: err, ErrHTTP: errHTTPBadRequest}
		}
	}
	return store.SanitizeError(err)
}
