## SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
version: '3.4'
services:
  yb-manager:
    image: yugabytedb/yugabyte:latest
    container_name: yb-manager-n1
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
               "--master_addresses=yb-manager-n1:7100",
               "--replication_factor=1"]
    networks:
      - hooks
    ports:
      - "7111:7000"
    environment:
      SERVICE_7000_NAME: yb-manager

  yb-tserver:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n1
    volumes:
      - ./docFiles/create_db.cql:/create_db.cql
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
               "--tserver_master_addrs=yb-manager-n1:7100"]
    networks:
      - hooks
    ports:
      - "9042:9042"
      - "6379:6379"
      - "5433:5433"
      - "9000:9000"
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - yb-manager
  yb-tserver-n2:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n2
    volumes:
      - ./docFiles/create_db.cql:/create_db.cql
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
               "--tserver_master_addrs=yb-manager-n1:7100"]
    networks:
      - hooks
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - yb-manager
networks:
  hooks:
